### ISSUE TITLE
Should we use YAML rather than JSON?

### ISSUE THREAD

**Issue by lehors** [lfai/model_openness_tool#15]
The data we are dealing with serializes just as well in YAML than JSON and YAML is much simpler to work with than JSON.
We might want to switch from downloading JSON files to downloading YAML files, or at least provide that as an option.

**Comment by gregcube** [comment]
I like the idea of using YAML rather than JSON. Drupal is more YAML-oriented in terms of its configuration management.

I suggest renaming `Download JSON` to simply `Download` and providing a hover-activated dropdown menu that allows the user to select either YAML or JSON as the format. Since JSON is already implemented, this approach seems best to me.

**Comment by lehors** [comment]
Addressed by PR #21 and PR #31
